//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStoreDB1
{
    using GameStoreDB1.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameStoreLegacy_dbEntities : DbContext
    {
        public GameStoreLegacy_dbEntities()
            : base("name=GameStoreLegacy_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<AccType> AccTypes { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Console> Consoles { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameSystem> GameSystems { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<AddingItem> AddingItem { get; set; }
    }
}
